### ISSUE TITLE
[Suggestion] Google Cardboard Support?

### ISSUE THREAD

**Issue by benbristow** [SDLash3D/xash3d-android-project#10]
I don't know if it's possible with this engine/game, but it'd be really awesome if somehow there could be some form of Google Cardboard support. 

VR Black Mesa Train Ride would be godlike.

**Comment by a1batross** [comment]
Interesting feature... Need to watch how it can be implemented in Java. Maybe some features must be done in engine or client library.

**Comment by a1batross** [comment]
Can I close this? We're still waiting for headtracking code from @Solexid.

**Comment by a1batross** [comment]
Done in a separate engine modification by @Solexid.
