### ISSUE TITLE
won't load!

### ISSUE THREAD

**Issue by mitchinx** [SDLash3D/xash3d-android-project#11]

**Comment by a1batross** [comment]
Hi,

Engine searches game data in /sdcard/xash folder, so your valve folder must
be copied as /sdcard/xash/valve.

Also, some Android vendors names /sdcard for phone memory and /sdcard1 for
SDcard. Try to put xash/ folder to phone memory.

14:35, сб, 01.08.2015, mitchinx <notifications@github.com>:

**Comment by valgusk** [comment]
On newest androids I thing it would be /storage/emulated/0/xash
