### ISSUE TITLE
Generic controller support

### ISSUE THREAD

**Issue by valgusk** [SDLash3D/xash3d-android-project#12]
As far as I understand,  only MOGA is supported,  can you please add generic controller support? Can't appreciate touch controls after I bought my dualshock

**Comment by a1batross** [comment]
Controllers are supported. Write "joystick 1" in console. But here is bugs that come from original HL: it's impossible to climb up on a ladder or push objects. 

So download any software that will emulate keyboards and bind it in game. For example, Sixaxis Controller can do it.

**Comment by valgusk** [comment]
thank you, joystick 1 worked, will need to dig in customizing input though. The bug you mention is unavoidable without remappers? If so, its really sad, as i am not rooted, my phone supports the controller natively.
