### ISSUE TITLE
Controller not really natively supported

### ISSUE THREAD

**Issue by valgusk** [SDLash3D/xash3d-android-project#13]
"JOY1" isn't a valid key

From log

Only axes work and can be configured. Please close if it is not the port issue

**Comment by a1batross** [comment]
AFAIK, there is must be gamecontrollerdb.txt in /sdcard/xash. 

For example, here is for.GameKeyboard:
**67616d656b6579626f61726400000000,GameKeyboard,platform:Android,a:b0,b:b1,x:b2,y:b3,start:b6,leftstick:b7,rightstick:b8,leftshoulder:b9,rightshoulder:b10,dpup:b11,dpdown:b12,dpleft:b13,dpright:b14,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5**

All found controllers are written in console.

**Comment by valgusk** [comment]
OK, so I should somehow replace contents of it, could try. About the console, its not showing. https://youtu.be/zlzhnSaZ1rs
I tried with " -console" and " -dev -console"

**Comment by a1batross** [comment]
Xash by defaults don't enables console. You must go to the valve folder,
open.gameinfo
txt and replace secure "1" to secure "0".

12:10, пн, 10.08.2015, Valery Guskov <notifications@github.com>:

**Comment by valgusk** [comment]
ok, thanks to you i have compiled correct mapping for controller. Now it outputs button numbers when i press buttons on gamepad, but assigning to e.g. JOY1 is still not working. If i assign "+jump" to it and then press correspondng button, it outputs "Button 1 pressed", but does not jump.

**Comment by valgusk** [comment]
ok, this belongs to xash3d repo i guess
https://github.com/SDLash3D/xash3d/blob/f63f0d3d3269b4b2cf521a31b33bdbd13a402fd3/engine/common/keys.c does not define joyN keys, only aux. While https://github.com/SDLash3D/xash3d/blob/e5714784c66367c6be0eee6fbcbc233f3c2ef945/engine/keydefs.h defines constants for joyN keys, not used anywhere i guess. Is it possible to move this issue to corresponding repo?

**Comment by valgusk** [comment]
for now, edited my controller mapping in mentioned gamecontrollerdb.txt file, in the end sacrificing only 2 buttons, as only Joy1-4 do not work. AUX5+ work ok

**Comment by jacobsindico1028** [comment]
I'm using 18.1 and I dont know how to configure the controls for my Ipega controller
