### ISSUE TITLE
Bluetooth mouse support and other questions

### ISSUE THREAD

**Issue by benjaminfoo** [SDLash3D/xash3d-android-project#22]
Hello world, 

I'd love to use my bluetooth mouse like in the original goldsrc engine games; I'd also hack myself into the source but im currently limited to develop on my android tablet with AIDE (its a great tool, check it out) ... I can checkout the repos from github, I can build nearly everything with it, excluding the sdl2-fork, which blocks my development progress completly - so is there a way of providing a prebuilt *.so file of the fork in some way? 

I've also some ideas for the launcher app, like automatic game discovering, mod downloading, fancy ui stuff, etc. - as a android developer I'd say we could create some sweet stuff. 

P.M. - I'm able to compile the android project with my Samsung Galaxy Note 10.1 with the latest AIDE release running Android 5.1. When I try to launch the fresh built project, I get an error message which displays a notification for the missing sdl2 binary (*.so). So if somebody could provide a release, wonderful things could happen :)

**Comment by a1batross** [comment]
Hi, I'm glad to see anyone that interested in developing. :)

Sdl2 fork is here: https://github.com/mittorn/SDL-mirror. 

Also, for build SDL version, you must call ndk-build with XASH_SDL=1 argument. NoSDL version is not working. %)

Bluetooth mouse are working, with evdev support. But it require root and some work with console commands.

**Comment by mittorn** [comment]
You need to change CFLAGS to compile with AIDE.
It has problems with vfp support. Weapons are disappeared if compiling without -msoft-float. Hard-fload needs to be disabled. Force enable XASH_SDL in Application.mk

**Comment by benjaminfoo** [comment]
So I just have to checkout the android-, hlsdk- and touch controls project  and symlink them properly.
Ill then import the android project with AIDE, navigate to the Application.mk file under xash3d-android-project/jni/ and change the right values... ill try this!

**Comment by mittorn** [comment]
check if SDL_PATH specified correctly.

**Comment by seece** [comment]
You should also change the Android version to 15 in `project.properties. This is done via sed in [the Travis builds](https://travis-ci.org/SDLash3D/xash3d-android-project#L907):

    sed -i -- s/android-8/android-15/g project.properties

**Comment by a1batross** [comment]
What is the point of issue? :)

**Comment by a1batross** [comment]
Issue not valid.
