### ISSUE TITLE
Touchscreen interface won't appear if you run Blue Shift Launcher before the main Xash Launcher

### ISSUE THREAD

**Issue by The-MAZZTer** [SDLash3D/xash3d-android-project#24]
If you run the BS Launcher and try to go in-game, the touchscreen interface won't appear. You need to have launched Xash at least once before. Once you do that, the touchscreen interface shows up in BS.

I had upgraded from the older release of xash before doing this, if it matters. I had run the older version of xash, just not the newer one.

I am guessing there is some first run configuration file generation or something that happens when you launch xash that is not happening if you run the BS Launcher.

Reproduction steps:
1. Run old xash release.
2. Upgrade to new release, load in bshift as well.
3. Run BS Launcher, try to go in-game. Note there are no controls.
4. Run Xash Launcher. Go in game, note there is a touchscreen interface.
5. Go back to BS Launcher and note the interface is back when you go in game this time.

**Comment by a1batross** [comment]
New version is unpacking controls to gamedir/controls directory. Old BS Launcher just don't doing this. 

I think unpacking controls must be moved to SDLActivity, so controls will be unpacked with every mod launcher.

**Comment by mittorn** [comment]
This is because touch contorls is disabled by default in SDLActivity. It's enabled when you run new xash3d launcher first time.
May be fixed by replacing false by true in SDLActivity.java when getting this preference.

**Comment by a1batross** [comment]
Not actual since using Native @mittorn's controls.
