### ISSUE TITLE
If you run BS and then Half-Life without closing BS, Xash gets confused and runs BS.

### ISSUE THREAD

**Issue by The-MAZZTer** [SDLash3D/xash3d-android-project#25]
Steps (note: Your device must have enough memory that it won't close BS once you task switch away. I suspect this won't work if you don't):
1. Run BS Launcher and observe the main menu of Blue Shift.
2. Tap home. Don't swipe away Xash on the recents screen.
3. Load Xash and run Half-Life.
4. Observe Xash Error: "Mem_FreePool: pool already free (freepool at jni/src/Xash3D/xash3d/engine/client/cl_game.c:3979)"
5. Tap OK button on error dialog.
6. Observe Blue Shift main menu instead of expected Half-Life main menu.

The error might be a red herring, I dunno. In any case, xash should kill any existing running xash when you are starting a new one from the launcher, unless resuming the current one is desired. Then it should have a way to determine if it is the mod it is expecting to see, and killing it and restarting it if it isn't.

**Comment by mittorn** [comment]
Android dows not support to run multiple instances of activity in different processes, so it cannot be fixed without running engine in separate non-java process. It is not possible now as separate processes cannot use opengl and user interfaces on android.
You may try to clone apk with different package name if you want to run several instances of the game, but then you will have problems with config.
