### ISSUE TITLE
Pressing back button in-game causes unexpected behavior.

### ISSUE THREAD

**Issue by The-MAZZTer** [SDLash3D/xash3d-android-project#26]
Steps:
1. Run BS Launcher.
2. Start Hazard Course.
3. Press back button.

What I expect to see: Main menu (as if the user pressed Escape) or nothing happens, or something else.

What I saw: Activity switched to the BS Launcher activity (behavior appears to be default for back button). When I press "Launch" again, I get the following error:

"Mem_Free: trashed header sentinel 1 (alloc at <corrupted>:0, free at jni/src/Xash3D/xash3d/engine/common/keys.c:280)"

and then Xash crashes, returning to the launcher.

**Comment by mittorn** [comment]
This is because engine launches second time in the same process. Use you recent tasks switcher to switch back to xash3d engine.

**Comment by The-MAZZTer** [comment]
I haven't checked BS but this seems to work in Half-Life.

**Comment by The-MAZZTer** [comment]
Yeah, works in BS too.
