### ISSUE TITLE
Menu button does nothing.

### ISSUE THREAD

**Issue by The-MAZZTer** [SDLash3D/xash3d-android-project#27]
Xash displays the triple-dot/menu button on the nav bar when running, but this button does not seem to do anything.

It should either be hidden to comply with the latest Android UX stuff, or it should at least be made to do something useful (like bound to the Escape key to open the menu).

Even if it is hidden it could still be useful for users with hardware keys with a menu button, or users of custom ROMs who force it visible.

**Comment by a1batross** [comment]
It's bindable to AUX30 key. 
Try to execute this in console
> bind AUX30 +jump
and then press your menu key. :)
