### ISSUE TITLE
Nothing happens after selecting difficulty.

### ISSUE THREAD

**Issue by testinglol** [SDLash3D/xash3d-android-project#3]
I'm on Nexus 5 running Android 5.1.1. I can get to main menu but when I click new game and then press any difficulty, nothing happens. The game doesnt start.
 Logcat
http://pastebin.com/pbxuRR28

Engine.log
http://pastebin.com/HKg3p8gu

**Comment by a1batross** [comment]
1) Is you copied game data to /sdcard/xash? 
/sdcard/xash/valve -- valve folder from your PC. 
2) Check gameinfo.txt for valid map names. startmap must be "c0a0".

**Comment by testinglol** [comment]
1) Yes I did.

2) It is c0a0

**Comment by testinglol** [comment]
It worked after using another program to move the files. Thanks tho
