### ISSUE TITLE
When weapon selector keys (the numbers) overlap other controls on the touchscreen, both are activated on touch.

### ISSUE THREAD

**Issue by The-MAZZTer** [SDLash3D/xash3d-android-project#30]
This is easiest to see in the default touchscreen configuration with the 0 key and the crouch button. When you press and hold 0 you will also crouch.

This also applies to the regions for moving or looking. If I hold 7 and move my finger, I look around.

Those keys should be "on top" of all other controls when active and a finger press on those numbers should not activate other controls.

The inverse is also true; if I hold on the move or look areas and move my finger onto a number, the number press should be ignored and I should be able to keep moving/looking with my finger. At least, that is what makes sense to me...

**Comment by a1batross** [comment]
It's a "feature" of Beloko's touchcontrols. 
Every overlapped buttons will be activated on touch.
