### ISSUE TITLE
Showing menu button like old app

### ISSUE THREAD

**Issue by th--** [SDLash3D/xash3d-android-project#35]
On my HTC One m7 (Android 5.0.1) i have an float menu button for compatible (like old application) after last update. Please fix this.
![screenshot_2015-09-13-18-37-40](https://cloud.githubusercontent.com/assets/3853486/9837426/ef67f56c-5a46-11e5-9c58-47e4b98bbae4.png)

**Comment by a1batross** [comment]
Not a bug. You can bind menu key to some action. Same for volume keys.
