### ISSUE TITLE
Opposing forces + suggestion

### ISSUE THREAD

**Issue by Mksands** [SDLash3D/xash3d-android-project#36]
Hello, I've found this app through YouTube tutorials on half life for android xash3d. I'm curious if in the next version opposing forces will have its own launcher to fix the problems and glitches it has when running . Ex: intro crashes, weapons stay the same as Half-Life weapons. I've enjoyed playing blue shift as well as the regular Half-Life so thank you very much. I've tried playing Half-Life: decay with my wife and it works through xash3d except for eye scanners not showing up and some scripted sequences not working. But it would be awesome to have more support forH Half-Life: Decay as it seems part of the half life collection (being as it's ported from ps2) . But anyways I've just been checking up on this website to see if there's a new release or not. Love this app and a huge Half-Life fan, thank you!

**Comment by a1batross** [comment]
Thanks for feedback! 

There is no source code for Opposing Force. Gearbox for some reason didn't released SDK.

Since Xash is better for multiplayer, coop is very good idea. I mailed Decay devs few weeks ago, but they don't replying. :(

**Comment by Mksands** [comment]
Awe man thats too bad. And crazy! Ya that would be way awesome. Decay seems way fun if it works all the way through. Hopefully developers will get back with ya! And thanks for getting back with me. I just have one more wish, dont know if its been brought up or not but the "thirdperson" console cheat for half-life works but only if your facing a certain direction otherwise itll glitch the screen into squares. I could bring up a new issue with it if you want.

**Comment by nate44** [comment]
Can tfc (team fortress classic) be made fully compatible. It works, but doesn't use the classes or any of the tfc weapons.
