### ISSUE TITLE
Touchscreen buttons appear as white squares

### ISSUE THREAD

**Issue by Manu270891** [SDLash3D/xash3d-android-project#37]
Using Xash3D 0.15 on my Nexus 9, I can't seem to get to touchscreen buttons to show properly. a "controls" folder is created in the "xash" folder, right next to the "valve" and "bshift" folders. Copying the "controls" folder inside the "valve" or "bshift" folders doesn't help either.

**Comment by a1batross** [comment]
Is "controls" folder contains any PNG files?

**Comment by Manu270891** [comment]
Yes,  40 png files.

**Comment by ledoge** [comment]
I also have this issue on my Nexus 9, on 5.1.1 stock ROM.

**Comment by mittorn** [comment]
It seems to be related to GPU driver. 
Controls are drawed now via hack.
It will be fixed after creating native controls

**Comment by a1batross** [comment]
Native controls is done.
So.. why it still open?
