### ISSUE TITLE
Does not launch mods

### ISSUE THREAD

**Issue by kuwoh** [SDLash3D/xash3d-android-project#38]
it doesn't seem to launch anything but half life and it also shows somekind of distortion to the ui
what im talking about is this (screen shot): http://puu.sh/kgBhh.jpeg

Device Info:
Samsung Galaxy II
Android 2.3.3

**Comment by a1batross** [comment]
(Err, how to rename an issue >_<)

It's only happens in Menu UI? What's in game? If you can't launch game from menu, just add +map c1a0 in command line args. 

Also I think you're launching mods wrong. You must add +game moddir to command line args.

**Comment by kuwoh** [comment]
well i did what you said on how to launch mods and it does that menu ui thing

**Comment by kuwoh** [comment]
tried what you said and still like that :/

**Comment by kuwoh** [comment]
weird now the ui is fine but.. it still wont launch mods i do it like this
+game tfc

**Comment by a1batross** [comment]
Nope. TFC doesn't work fully. (because it closed source)

**Comment by kuwoh** [comment]
how about cstrike it used to work man i tried it on my mom's phone

**Comment by a1batross** [comment]
cstrike NOT working too.

**Comment by kuwoh** [comment]
welll the ui is still screwed and the +map thing doesnt work

**Comment by Trolldozer128** [comment]
It's with a -, not a +. Or try making a shortcut.

**Comment by francazzo** [comment]
Hi, there. Many thanks for your e-mail!

However, my issue was slightly different: I can launch successfully most of
the mods. However, the majority of them (such as Gunman Chronicles) can be
launched perfectly, but have "empty" levels, with most of the characters
and 3d models missing.
I was told that this is to do with the mods' libraries, which should be
modified to work in Android with Xash3D. I guess, this is still the case,
and GunMan Chronicles would still launch, but with empty levels?

Thanks and regards.

Franco

**Comment by a1batross** [comment]
Without rewriting source code, you can run only Half-Life based mods. 

You may try XashDS Android. This is a Dedicated Server running in x86 emulator with Windows DLL support. If mod doesn't require special "libclient", it will run perfectly. Some people are using this to run opposing force on Android.

**Comment by francazzo** [comment]
Hi. Many thanks.

From what I can see, XashDS (unlike Half-Life from Xash3d) is not an
application, but is an on-line server. So, there is nothing that can be
installed on Android devices, and you need Wi-Fi always on, am I right?
If so, this is definitely a big downside, compared to Xash3D.
For the time being, I think, I will stick with Xash3D to run Half Life and
Blue Shift.
One day, somebody may convert some other Half Life mods, such as Gunman
Chronichles. If not, never mind.
Thanks again for all your work.

Best regards.

Franco

**Comment by a1batross** [comment]
No, XashDS Android is an app. 
It contains headless engine compiled for x86 linux and QEMU virtual machine.

**Comment by francazzo** [comment]
O.K., thanks.
Last time I was in a rush and I could find a link to the app. I will check
better and will definitely try it.
I will let you know for your interest if Gunman Chronicles works with all
the 3d models as in the PC version.
Thanks and regards.
Franco

**Comment by francazzo** [comment]
Hi, there.
I have finally managed to find time to download SDLash3D 1.03 apk and install it on various Android devices. These are the same devices where I already have successfully installed the glorious Xash3d apk (version 17.1, still the latest), with all the Half Life data and mods in the Xash directory.
My experience is that while Xash3D runs perfectly Half Life and Blue Shift, SDLash3D (using the same path working for Xash3D) does not manage to open anything on any of the devices.
Xash3D installed on my divices even manages to load successfully mods such as Gunman Chronicles, although as some of the models libraries are unsupported the levels appear working, but empty.
SDLash3D was supposed to help playing these mods, but it is simply not working. You can see a script appearing on the screen, and no error messages (the Half Life build engine is recognized), but nothing happens. I don't know if it's just me or if anybody has had more luck. Unfortunately, there is no tutorial or instruction available on-line.
Thanks and bye.
Franco

**Comment by francazzo** [comment]
...payment in cash or beer offered to whoever can make mods requiring windows dll support working on Android devices! :)

**Comment by a1batross** [comment]
It's possible to load a windows DLL on Android. But only server mods.

You can use mittorn's XashDS Android. It simply runs over virtual machine
and starts the dedicated server.

**Comment by francazzo** [comment]
Hi. Thanks, but please bear in mind that you are not talking to an expert...
If I have well understood, "server mods" in practice means only Multi-player mods, am I right?
So, no chance for mods like Gunman Chronicles (single player) requiring Windows dll libraries?

Note: are SDLash3D (apk currently at version 1.03, which I have downloaded and tried) and XashDS Android the same thing?

**Comment by nekonomicon** [comment]
>server mods
*server libraries for singleplayer mods with rcon and half life client library.

**Comment by a1batross** [comment]
I mean server DLL. In HL it named hl.dll, in CS mp.dll, in Op4 --
gearbox.dll and located in "dll" directory.

Latest Xash3D Android port is 0.17.1. O don't know what is the 1.03.

**Comment by francazzo** [comment]
Hi. Thanks, but your explanation still requires a minimum of programming
knowledge. It doesn't help me in practice understing what I have to do once
the SDLash3D app is installed on my phone, to try and make a Half-Life mod
working. I guess, I would need to go through a course to follow this
discussion: like this I will be kicked out soon, abusing of everyone's
patience...

Is there somewhere a simple step-by-step idiot-proof tutorial for the use
of the SDLash3D apk, useful to people like me who have no programming
knowledge whatsoever, but despite this still managed to get the Xash3D apk
working with Half Life and other mods? If not, I guess, I will have to give
up...

Bye.

**Comment by rea987** [comment]
Hi,

Has there been any development to run Gunman via Xash3D on Linux natively. It run via Windows branch but no luck with Linux so far.

https://youtu.be/_CZQUsyHhaU

Thanks, regards.

**Comment by mittorn** [comment]
Some modern mods will not work with dll loader because supporting new visual studio build is harder. We need to implement bigger part of Windows to run it, but we do not want to do it. Most of mods are built with msvc6-8 and should work if it does not interact with system too much

**Comment by a1batross** [comment]
Gunman Chronicles is an old mod. It should run with DLL loader.

Just try to specify DLL on Linux.

2017-10-03 17:17 GMT+03:00 mittorn <notifications@github.com>:

**Comment by rea987** [comment]
Sorry for ignorance; can you please tell me how to specify the dll on Linux? Any tutorial would be appreciated.

**Comment by mittorn** [comment]
find dll in mod/dlls folder.
first way is add "-dll dlls/smth.dll" to arguments, second is edit gameinfo.txt and change gamedll_linux

**Comment by rea987** [comment]
I copied valve and rewolf folders to xash3d_fwgs_linux directory. Game failed to launch, I needed to kill the process; here is the launch command and output;

```
$ sh xash.sh -rewolf -dll dlls/gunman.dll
================================================================================
	Xash3D FWGS (build 731, Linux-i386) started at Oct04 2017 [12:12.10]
================================================================================
Loader_LoadLibrary( "dlls/gunman.dll" )
Loader_LoadLibrary( "dlls/gunman.dll" )

================================================================================
	Xash3D FWGS (build 731) change game to 'Gunman Chronicles' at Oct04 2017 [12:12.20]
================================================================================
================================================================================
	Xash3D FWGS (build 731, Linux-i386) started at Oct04 2017 [12:12.20]
================================================================================
Loader_LoadLibrary( "dlls/gunman.dll" )
Loader_LoadLibrary( "rewolf/dlls/gunman.dll" )
Could not find KERNEL32.dll:FatalAppExitA
Could not find KERNEL32.dll:LCMapStringA
Could not find KERNEL32.dll:LCMapStringW
Could not find KERNEL32.dll:GetStringTypeA
Could not find KERNEL32.dll:GetStringTypeW
Could not find KERNEL32.dll:SetStdHandle
Could not find KERNEL32.dll:FlushFileBuffers
Could not find KERNEL32.dll:IsValidLocale
Could not find KERNEL32.dll:IsValidCodePage
Could not find KERNEL32.dll:EnumSystemLocalesA
Could not find KERNEL32.dll:GetUserDefaultLCID
Could not find KERNEL32.dll:RtlUnwind
Could not find KERNEL32.dll:UnhandledExceptionFilter
Could not find KERNEL32.dll:SetConsoleCtrlHandler
Could not find KERNEL32.dll:RaiseException
Could not find KERNEL32.dll:SetEndOfFile
Could not find KERNEL32.dll:GetLocaleInfoW
Could not find KERNEL32.dll:CompareStringA
Could not find KERNEL32.dll:CompareStringW
Loader_FreeLibrary( 0x10000000 )
[12:12:24] Sys_Warn: Could not load client library:
cl_dlls/client.so: cannot open shared object file: No such file or directory
client.so: cannot open shared object file: No such file or directory

Killed
```

I also tried to edit rewolf/gameinfo.txt;

`gamedll_linux		"dlls/gunman.dll"`

The result is the same;

```
$ sh xash.sh -rewolf
================================================================================
	Xash3D FWGS (build 731, Linux-i386) started at Oct04 2017 [12:15.56]
================================================================================
[12:16:02] Unknown command: VModEnable

================================================================================
	Xash3D FWGS (build 731) change game to 'Gunman Chronicles' at Oct04 2017 [12:16.13]
================================================================================
================================================================================
	Xash3D FWGS (build 731, Linux-i386) started at Oct04 2017 [12:16.13]
================================================================================
Loader_LoadLibrary( "dlls/gunman.dll" )
Loader_LoadLibrary( "rewolf/dlls/gunman.dll" )
Could not find KERNEL32.dll:FatalAppExitA
Could not find KERNEL32.dll:LCMapStringA
Could not find KERNEL32.dll:LCMapStringW
Could not find KERNEL32.dll:GetStringTypeA
Could not find KERNEL32.dll:GetStringTypeW
Could not find KERNEL32.dll:SetStdHandle
Could not find KERNEL32.dll:FlushFileBuffers
Could not find KERNEL32.dll:IsValidLocale
Could not find KERNEL32.dll:IsValidCodePage
Could not find KERNEL32.dll:EnumSystemLocalesA
Could not find KERNEL32.dll:GetUserDefaultLCID
Could not find KERNEL32.dll:RtlUnwind
Could not find KERNEL32.dll:UnhandledExceptionFilter
Could not find KERNEL32.dll:SetConsoleCtrlHandler
Could not find KERNEL32.dll:RaiseException
Could not find KERNEL32.dll:SetEndOfFile
Could not find KERNEL32.dll:GetLocaleInfoW
Could not find KERNEL32.dll:CompareStringA
Could not find KERNEL32.dll:CompareStringW
Loader_FreeLibrary( 0x10000000 )
[12:16:40] Sys_Warn: Could not load client library:
cl_dlls/client.so: cannot open shared object file: No such file or directory
client.so: cannot open shared object file: No such file or directory

Killed
```

I also tried to run the mod as a standalone game by renaming rewolf folder as valve, same result;

```
$ sh xash.sh
================================================================================
	Xash3D FWGS (build 731, Linux-i386) started at Oct04 2017 [12:21.52]
================================================================================
Loader_LoadLibrary( "dlls/gunman.dll" )
Loader_LoadLibrary( "valve/dlls/gunman.dll" )
Could not find KERNEL32.dll:FatalAppExitA
Could not find KERNEL32.dll:LCMapStringA
Could not find KERNEL32.dll:LCMapStringW
Could not find KERNEL32.dll:GetStringTypeA
Could not find KERNEL32.dll:GetStringTypeW
Could not find KERNEL32.dll:SetStdHandle
Could not find KERNEL32.dll:FlushFileBuffers
Could not find KERNEL32.dll:IsValidLocale
Could not find KERNEL32.dll:IsValidCodePage
Could not find KERNEL32.dll:EnumSystemLocalesA
Could not find KERNEL32.dll:GetUserDefaultLCID
Could not find KERNEL32.dll:RtlUnwind
Could not find KERNEL32.dll:UnhandledExceptionFilter
Could not find KERNEL32.dll:SetConsoleCtrlHandler
Could not find KERNEL32.dll:RaiseException
Could not find KERNEL32.dll:SetEndOfFile
Could not find KERNEL32.dll:GetLocaleInfoW
Could not find KERNEL32.dll:CompareStringA
Could not find KERNEL32.dll:CompareStringW
Loader_FreeLibrary( 0x10000000 )
[12:21:57] Sys_Warn: Could not load client library:
cl_dlls/client.so: cannot open shared object file: No such file or directory
client.so: cannot open shared object file: No such file or directory

Killed
```

Following list has been posted in 2012 and updated in 2014; it claims that,

> Gunman Chronicles (stand-alone game by Rewolf; build 2664 or newer is required to play the game properly)

Is the build of the engine or the mod/game itself incompatible?

**Comment by nekonomicon** [comment]
>$ sh xash.sh -rewolf -dll dlls/gunman

May be `-game rewolf`?

Also, dll loader - just wine-based wrapper for dlls. It's not working with some mods, because can't wrap some calls.

**Comment by francazzo** [comment]
Dear all,

My experience is only with Xash3D for Android (various versions): the
Gunman Chronicles mod launches perfectly and works O.K., but because most
of its dll libraries are not compatible, the game levels look empty. This
was expected, as explained to me by Alibek Omarov. It's a shame.

Regards to all.

**Comment by rea987** [comment]
@francazzo Then it is same as editing liblist.gam to run the game as Half-Life mod on Steam. Thanks for clarification.

**Comment by francazzo** [comment]
Hi. I guess, it must be like this: I'm not an expert, just a casual user:
all I have tried to do was checking which mods were fully compatible with
Xash3D for Android, but without touching any line of the code, just copying
and pasting folders. Only 8 - 10 mods (Blue Shift, Poke646, Vendetta, Times
of Troubles, Lost in Xen, Edge Of Darkness, and few others) are (or have
been made) fully compatible with Xash3d for Android, including all the 3D
models, and unfortunately Gunmand Chronicles in not one of them, for the
moment. My understanding from this conversation is that this is still the
case, with no easy fix for Android?

Regards.

**Comment by nekonomicon** [comment]
@francazzo, ~300 mods working without special launchers, ~30 with Spirit of Half-Life 1.2 launcher, ~20 with separate launchers, some mods working with xashds yet.
