### ISSUE TITLE
mods run with dev mod

### ISSUE THREAD

**Issue by gummy69** [SDLash3D/xash3d-android-project#39]
I have created mod shorcuts with the feature but they all run with the -dev command (stuff won't run, no weapon sounds & animations) even though I deleted the command from the base xash3d app. I just straight up used -game (foldername) from the xash3d app but it just runs original Half-Life and don't run mods. Can anyone help?

**Comment by mittorn** [comment]
try add some command line when creating shortcut. And don't forget to enable cl_lw.
If this mod uses modified libraries, it will not work correctly.
Libraries need to be ported separately.

**Comment by gummy69** [comment]
I have a new problem, in some mods and in the original HL, the view recenters everythimg so I can't aim, any solution?

**Comment by a1batross** [comment]
Enable Mouse Look in game settings. Fix will be included in new release.

**Comment by gummy69** [comment]
It looks like a whited out setting. Tapping on it doesn't seem to change anything.

**Comment by a1batross** [comment]
Ah... You just didnt extracted extras.zip. It included in EVERY release.
