### ISSUE TITLE
Andoeyo making internet games!

### ISSUE THREAD

**Issue by AICgmo** [SDLash3D/xash3d-android-project#41]
"-cl_predict 1 -cl_lw 1 -console" on the command line, but the input is not only possible to make a direct connection to the Internet game.

**Comment by a1batross** [comment]
What? You can create a local game in LAN game. To make internet server, I recommend to build XashDS -- dedicated version of engine and deploy it on your server with white IP.

Don't use cl_lw 1 on Android, it's not supported and will break your weapon animations.

**Comment by Trolldozer128** [comment]
Nearly did this, but read the consenquences. Thanks.
