### ISSUE TITLE
New games will appear when you press the only sound.

### ISSUE THREAD

**Issue by AICgmo** [SDLash3D/xash3d-android-project#44]
New games will appear when you press the only sound...

My phone is

Android Version:5.1.1

galaxy s6 edge-kt
(sm-g925k)

**Comment by a1batross** [comment]
What? How to reproduce?

**Comment by AICgmo** [comment]
Hm....I do not run. I want you to fix this error

**Comment by AICgmo** [comment]
After only sound I can hear even the difficulty at the start of the game. Android 5.1.1 is not ever going to do?

**Comment by a1batross** [comment]
I don't understand you.

**Comment by AICgmo** [comment]
Sorry...

It is not able to explain this lack of English language skills.

**Comment by a1batross** [comment]
You can record a video. :) 

Maybe it's just a problem of your game data.
