### ISSUE TITLE
Maybe make the internet better?

### ISSUE THREAD

**Issue by Trolldozer128** [SDLash3D/xash3d-android-project#48]
I get the fact how this is a different engine than Goldsrc (Possibly, as I found out that Xash3d was an engine mod for Half-Life soon after discovering this app), may use a different client, and is recommended to use LAN games, but please fix the internet. The game is always lagging whenever I try to join a server with at least 1 PERSON, and the game already lags. I feel like my character is doing constant 1 milisecond skips as my game gets very laggy and hard to control. Please find a way to allow us to play internet games (Like those servers on the original Half-Life that AREN'T empty) faster and easier.

**Comment by mittorn** [comment]
Just enable predict

**Comment by a1batross** [comment]
Client side.prediction.works.fine, but still experimental feature. To enable, write cl_predict 1 in console.
