### ISSUE TITLE
[Suggestion] The ProgressBar Style

### ISSUE THREAD

**Issue by steadyfield** [SDLash3D/xash3d-android-project#49]
Currently, the progressbar is "=========================="
I think it would look better if it is [#########________].

[#________________]
[#####____________]
[#########________] 50%
[#################] 100%

The waypoint generation progressbar of early version of CS1.6 CZBOT also use this style of progressbar

**Comment by a1batross** [comment]
https://github.com/mittorn/csdm/commit/37a3a64b0d61dc55e86c55190938b222f9beb94a

Look, here is a new progress bar. Just update to latest CSDM. 
https://github.com/mittorn/csdm-android/releases/tag/v0.2
