### ISSUE TITLE
Configurable path or /extSdCard/ path support

### ISSUE THREAD

**Issue by Blackbird88** [SDLash3D/xash3d-android-project#5]
So the game files can be stored on external SD Card since internal storage is usually limited.

**Comment by a1batross** [comment]
Path will be configurable in 0.15.
I'm just little busy for this two weeks so I can't fix it now.

**Comment by Blackbird88** [comment]
Cool thanks! I prefer to use my 32GB SD over my tiny 8GB storage.

**Comment by a1batross** [comment]
I will keep this open 'til this feature will not be implemented.

**Comment by a1batross** [comment]
Already done in 0.15 prerelease.

**Comment by Blackbird88** [comment]
Sweet! Thank you!
