### ISSUE TITLE
Please apply to these "string . xml" "0.17 beta".

### ISSUE THREAD

**Issue by AICgmo** [SDLash3D/xash3d-android-project#61]
Please apply to these "string . xml" "0.17 beta"....

My Email is
rnalsdn1234@naver.com

<?xml version="1.0" encoding="UTF-8"?>

-<resources>

-<string name="git_revisions">

<b>버젼 정보:</b>
test build\n
<b>안드로이드:</b>
bab2279 Update engine \n
<b>엔진:</b>
8159a72 Add additional name check to prevent another way to become invisible \n
<b>클라이언트:</b>
bab2279 Update engine \n
<b>하프라이프:</b>
0e9f18d Merge pull request #7 from nekonomicon/master \n
<b>SDL2:</b>
1f0b6dd xash3d config \n
<b>호외:</b>
501f577 Use TGA with RLE compression instead of LARGE bmps \n
<b>나노gl:</b>
5ea04e4 Merge pull request #3 from mittorn/master\nmittorn@localhost 11:18:57-31-01-16
</string>

<string name="app_name">Xash3D</string>

<string name="launcher_name">Xash3D</string>

<string name="launcher_name_test">Xash3D (테스트)</string>

<string name="launch_button">Xash3D 실행!</string>

<string name="cmd_args_text">커멘드 라인 입력(고급 설정)</string>

<string name="use_controls">터치 컨트롤 사용</string>

<string name="use_volume">볼륨키 사용</string>

<string name="text_res_path">게임 리소스 위치</string>

<string name="touch_set">컨트롤 설정</string>

<string name="text_shortcut">Xash3D 바로가기</string>

<string name="text_shortcut_test">Xash3D_테스트 바로가기</string>

<string name="shortcut_button_save">바로가기 저장</string>

<string name="gamedir">모드 디렉토리</string>

<string name="pkgname">모드 패키지 이름(고급설정)</string>

<string name="shortcut_name">바로가기 이름</string>

<string name="about_main">Xash3D 안드로이드</string>

<string name="about_copyright">우리 SDLash3D는 밸브와 상업적으로 관련이 없습니다. 모든 저작권은 소유주로 보류되어있음을 알립니다..</string>

<string name="version_string">v0.17</string>

<string name="about_authors">안드로이드 이식 by SDLash3D팀: \n • a1batross\n • mittorn \n • nicknekit.\n 특별히 감사드리는 것들:\n • 마이클삼촌의 XASH3D엔진\n • 밸브의 하프라이프\n • libSDL2 개발자분들\n • 한글화 byAIC from X3A NaverCafe</string>

-<string name="about_links">
여기서 우리를: • 
<a href="https://vk.com/xashdroid">VK</a>
• 
<a href="http://moddb.com/game/xash3d-android">모드디비</a>
• 
<a href="https://github.com/SDLash3D">깃허브</a>

</string>

<string name="about_button">Xash3D 안드로이드 정보</string>

<string name="create_shortcut_button">바로가기 만들기</string>

<string name="select_folder">(선택)</string>

</resources> 

@mittorn

**Comment by a1batross** [comment]
Can you send it as a Pull Request?
I can't apply it, because GitHub removed all XML tags.

**Comment by a1batross** [comment]
Added to mainstream. 
Found a way how to extract XML from Issue. Just enter editing. :)
