### ISSUE TITLE
Does not recognise 'valve' directory

### ISSUE THREAD

**Issue by zeropointsoftware** [SDLash3D/xash3d-android-project#63]
Does not recognise 'valve' directory, and gives odd errors to state this fact.

Running Australian Optus 5.0.1 on a Note 4, using Steam Half-Life version "1.1.2.2/Stdio"
Recently updated system to 5.1.1, gives same results as below.

If I use the inbuilt file/directory selector to select the location of the valve directory where I've copied the game materials, it gives: 
"Changing working directory to /storage/emulated/0/sdcard/xash/valve failed."

If I follow the instructions and manually specify /sdcard/xash/valve as the directory, it gives the same error.

Samsung's inbuilt file manager, "My Files" gives the directory path where I've copied them as "/storage/extSdCard/xash/valve"
If I manually specify the path to this it tells me "Cannot find the directory 'valve'.".

If I deliberately mis-spell the dorectory path, it gives me "Cannot find the directory 'valve'.".

If I append a / to the end of any of the above directory paths, it gives me the same error as if I didn't add the extra slash (which at least makes sense).

**Comment by a1batross** [comment]
You must specify path *without* "valve" in launcher. Because it root
directory, where engine will look for games.

Try to set /storage/extSdCard/xash.

**Comment by zeropointsoftware** [comment]
>You must specify path *without* "valve" in launcher.
...I swear to god I tried that early on. Works perfect and smooth as butter on the Note 4.
Awesome, thanks!
