### ISSUE TITLE
Decal Limit

### ISSUE THREAD

**Issue by FalconTR** [SDLash3D/xash3d-android-project#64]
First of all I appreciate all of your work, you guys are doing awesome work. The issue is: game gets fps drops when there are a lot of decals/particles. In PC version there was an option to set decal limit. Hope you'll fix it.

**Comment by a1batross** [comment]
r_decals X. Where is X -- maximum count of decals.

It's somehow works in GS with mp_decals. But Xash3D doesn't support it.

**Comment by FalconTR** [comment]
Allright r_decals works perfectly thanks a lot. And also; 
1.What does tduck do
2.Are you going to add longjump button? 
Long jumping works like a one button when I joint the duck and jump buttons like this![c1a1](https://cloud.githubusercontent.com/assets/17477627/13326435/87327b0a-dbee-11e5-95e8-bba01925a695.png)

**Comment by a1batross** [comment]
This controls is fully scriptable. You can add your own cool buttons in
menu or by hand, in config files.

Look xash-extras repo for reference.
