### ISSUE TITLE
No armory in blue shift,freeman hands instead of calhoun

### ISSUE THREAD

**Issue by gzdoomer** [SDLash3D/xash3d-android-project#67]
Hello

I have this some kind of a bug that whenever I play blue shift in course or single player I usually don't get armor and helmet and also I see that the character you play is having Gordon freeman hands

Maybe it's because there is not libserver implementation?

Hope you answer

**Comment by nekonomicon** [comment]
Lol, use bs-launcher for Blue Shift.

https://github.com/mittorn/BS-android/releases

**Comment by gzdoomer** [comment]
OK now the first one fixed (thanks!)
But the second one(freeman hands) is still there any suggestions?

**Comment by a1batross** [comment]
I think it's broken view models.

**Comment by nekonomicon** [comment]
>But the second one(freeman hands) is still there any suggestions?
Needs normal cache from steam with barney.wad.
I can't reproduce any bugs.
