### ISSUE TITLE
Oh! Textur Error!

### ISSUE THREAD

**Issue by AICgmo** [SDLash3D/xash3d-android-project#68]
" 0.17 " beta is functioning normally , but " 0.17 " is generated 'm a texture error.

Screenshot here
http://mblogthumb3.phinf.naver.net/20160403_62/rnalsdn1234_1459650072175GAsjc_PNG/Screenshot_2016-04-03-11-08-34.png?type=w2

**Comment by nekonomicon** [comment]
It's crappy fix into nanogl repo.
Update coming soon.
