### ISSUE TITLE
how to compile? / como compliar?

### ISSUE THREAD

**Issue by henryvc** [SDLash3D/xash3d-android-project#69]
**********************************************************************************************************************
English
1 * hello, excuse my question is very basic but I'm new to this and do not know how that program or softeare is required to compile the code,
I have installed
"Android Studio"
"Android NDK"
2 * than other software need to compile
3 * I have also downloaded these projects
"Hlsdk-xash3d-master"
"MobileTouchControls-master"
"Nanogl-master"
"SDL-mirror-master"
"Xash3d-master"
"XASH-extras-master"
4 * We also have created links in the folder C:\temp\xash3d-android-project-0.16.1\jni\src\xxx
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\hlsdk-xash3d-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\MobileTouchControls-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\nanogl-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\SDL-mirror-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\xash3d-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\xash-extras-master
5 * and most importantly that the steps to compile the code
Thanks for your time to read my doubts

*******************************************************************************************************************
ESPAÑOL
como compliar?

1*hola, perdonen mi pregunta que es muy basica pero soy nuevo en esto y no se como hacerlo, que programa o softeare es necesario para compilar el codigo, 
tengo instalado 
"Android Studio" 
"Android NDK"
2*que otro software necesito para compilar 
3* Tambien he descargado estos proyectos
"hlsdk-xash3d-master"
"MobileTouchControls-master"
"nanogl-master"
"SDL-mirror-master"
"xash3d-master"
"xash-extras-master"
4*Tambien he creado links dentro de la carpeta C:\temp\xash3d-android-project-0.16.1\jni\src\xxx
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\hlsdk-xash3d-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\MobileTouchControls-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\nanogl-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\SDL-mirror-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\xash3d-master
MKLINK /D halflife D:\Android\HalfLife\SourceCode\Requeridos\xash-extras-master
5* y lo mas importante que pasos debo seguir para compilar el codigo

Gracias por su tiempo en leer mis dudas

**Comment by a1batross** [comment]
We don't support Android Studio in any way.

Building is very simple. You'll need Git, Python, JDK and NDK. 
For reference, you may look into our build.sh or .travis.yml.

**Comment by DeicPro** [comment]
@a1batross I'm confused.

What I need to build APK?

**OS installed**
Ubuntu 16.04 x86_64
**Programs installed**
git
python
openjdk-8-jdk
android-headers
**Building process**
```
wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
chmod +x android-ndk-r10e-linux-x86_64.bin && ./android-ndk-r10e-linux-x86_64.bin > /dev/null
mv android-ndk-r10e android-ndk
export PATH=`pwd`/android-ndk:`pwd`/android-sdk-linux/tools:`pwd`/android-sdk-linux/platform-tools:$PATH
```
and...
```
git clone https://github.com/SDLash3D/xash3d-android-project.git
cd xash3d-android-project
git submodule init && git submodule update
```
then
```
sh build.sh
```
and I get this:
```
build.sh: 3: build.sh: ndk-build: not found
<?xml version="1.0" encoding="utf-8"?>
<resources>
<string name="git_revisions"><b>Version information:</b>  default-release\n<b>android:</b> 71f1aa6 Create strings.xml (#99) \n<b>engine:</b> 0bfac66 Add NAN check to prevent infinite loop \n<b>hlsdk:</b> 5d96c43 Fix crash \n<b>SDL2:</b> 1f0b6dd xash3d config \n<b>extras:</b> 58d6e0d Add joystick texture \n<b>nanogl:</b> 51ccb8d Revert "fix glGetError"\nroot@deic-Presario-CQ57-Notebook-PC 10:47:05-10-05-16</string>
</resources>
pak: fastdl.txt
pak: gameinfo.txt
pak: credits.txt
pak: touch_default/key_8.tga
pak: touch_default/flash_light_filled.tga
pak: touch_default/keyboard.tga
pak: touch_default/key_6.tga
pak: touch_default/key_3.tga
pak: touch_default/map.tga
pak: touch_default/use.tga
pak: touch_default/joy.tga
pak: touch_default/shoot.tga
pak: touch_default/settings.tga
pak: touch_default/numbers.cfg
pak: touch_default/key_5.tga
pak: touch_default/key_4.tga
pak: touch_default/save.tga
pak: touch_default/prev_weap.tga
pak: touch_default/key_0.tga
pak: touch_default/key_2.tga
pak: touch_default/load.tga
pak: touch_default/edit_show.tga
pak: touch_default/edit_reset.tga
pak: touch_default/next_weap.tga
pak: touch_default/key_7.tga
pak: touch_default/key_1.tga
pak: touch_default/reload.tga
pak: touch_default/key_9.tga
pak: touch_default/tduck.tga
pak: touch_default/shoot_alt.tga
pak: touch_default/edit_hide.tga
pak: touch_default/gamma.tga
pak: touch_default/jump.tga
pak: touch_default/crouch.tga
pak: touch_default/License.txt
pak: touch_default/edit_close.tga
pak: touch_default/show_weapons.tga
pak: media/launch_glow1.wav
pak: media/launch_deny2.wav
pak: media/launch_dnmenu1.wav
pak: media/launch_deny1.wav
pak: media/launch_upmenu1.wav
pak: media/launch_select2.wav
pak: media/launch_select1.wav
pak: gfx/shell/head_filter.tga
pak: gfx/shell/head_touch_options.tga
pak: gfx/shell/scrn.tga
pak: gfx/shell/min_n.tga
pak: gfx/shell/larrowpressed.tga
pak: gfx/shell/head_save.tga
pak: gfx/shell/uparrowf.tga
pak: gfx/shell/head_readme.tga
pak: gfx/shell/dnarrowd.tga
pak: gfx/shell/head_creategame.tga
pak: gfx/shell/rarrowdefault.tga
pak: gfx/shell/cb_down.tga
pak: gfx/shell/down.tga
pak: gfx/shell/kb_keys.lst
pak: gfx/shell/head_lan.tga
pak: gfx/shell/cb_checked.tga
pak: gfx/shell/btn_touch_buttons.tga
pak: gfx/shell/slider.tga
pak: gfx/shell/head_custom.tga
pak: gfx/shell/notsecure.tga
pak: gfx/shell/head_controls.tga
pak: gfx/shell/head_advoptions.tga
pak: gfx/shell/lock.tga
pak: gfx/shell/Colors.lst
pak: gfx/shell/uparrowp.tga
pak: gfx/shell/btn_touch_save.tga
pak: gfx/shell/head_load.tga
pak: gfx/shell/splash.tga
pak: gfx/shell/nonfav.tga
pak: gfx/shell/kb_def.lst
pak: gfx/shell/cls_d.tga
pak: gfx/shell/divider.tga
pak: gfx/shell/head_touch.tga
pak: gfx/shell/head_rooms.tga
pak: gfx/shell/head_vidoptions.tga
pak: gfx/shell/head_saveload.tga
pak: gfx/shell/head_gameopts.tga
pak: gfx/shell/btn_touch_select.tga
pak: gfx/shell/kb_act.lst
pak: gfx/shell/larrowdefault.tga
pak: gfx/shell/btn_touch_reset.tga
pak: gfx/shell/head_config.tga
pak: gfx/shell/cb_over.tga
pak: gfx/shell/btn_touch_options.tga
pak: gfx/shell/head_single.tga
pak: gfx/shell/cb_empty.tga
pak: gfx/shell/btn_touch_editor.tga
pak: gfx/shell/head_audio.tga
pak: gfx/shell/font.tga
pak: gfx/shell/sm_dnarw.tga
pak: gfx/shell/cls_f.tga
pak: gfx/shell/head_customize.tga
pak: gfx/shell/min_d.tga
pak: gfx/shell/listen.tga
pak: gfx/shell/head_newgame.tga
pak: gfx/shell/favorite.tga
pak: gfx/shell/head_touch_buttons.tga
pak: gfx/shell/head_video.tga
pak: gfx/shell/head_keyboard.tga
pak: gfx/shell/head_specgames.tga
pak: gfx/shell/head_multi.tga
pak: gfx/shell/head_room.tga
pak: gfx/shell/up.tga
pak: gfx/shell/head_vidmodes.tga
pak: gfx/shell/head_record.tga
pak: gfx/shell/head_createroom.tga
pak: gfx/shell/head_gore.tga
pak: gfx/shell/head_playrec.tga
pak: gfx/shell/gamma.tga
pak: gfx/shell/uparrowd.tga
pak: gfx/shell/larrowflyover.tga
pak: gfx/shell/rarrowflyover.tga
pak: gfx/shell/btns_main.bmp
pak: gfx/shell/dnarrowf.tga
pak: gfx/shell/head_inetgames.tga
pak: gfx/shell/head_play.tga
pak: gfx/shell/unlock.tga
pak: gfx/shell/cls_n.tga
pak: gfx/shell/secure.tga
pak: gfx/shell/dnarrowp.tga
pak: gfx/shell/min_f.tga
pak: gfx/shell/head_advanced.tga
pak: gfx/shell/rarrowpressed.tga
pak: gfx/shell/sm_dnarf.tga
pak: gfx/shell/btn_touch.tga
pak: gfx/shell/cb_disabled.tga
build.sh: 7: build.sh: ant: not found
(1*) Enter Passphrase for keystore: 
jarsigner error: java.lang.RuntimeException: keystore load: /home/deic/xash3d-android-project/../myks.keystore (No existe el archivo o el directorio)
rm: no se puede borrar 'bin/xashdroid-release.apk': No existe el archivo o el directorio
(2*) build.sh: 10: build.sh: /home/a1ba/.android/android-sdk-linux/build-tools/22.0.1/zipalign: not found
```
1* I don't know what to put here
2* I know I have to change the user, but same I don't have .android dir

**Comment by a1batross** [comment]
Script says that you don't have Apache Ant and ndk-build.

I see, you have unpacked NDK, so just fix PATH variable. Ant can be
installed from repos.

**Comment by DeicPro** [comment]
@a1batross Looks like Github email notifications ignore comments edited xD...

I did that stuff, read again my last reply please :).

**Comment by firminoveras** [comment]
no way for Windows? :/

**Comment by DeicPro** [comment]
@a1batross 
´´´
sudo apt install lib32stdc++6 lib32z1
´´´
Now aapt "exist" and all work fine. :)

**Comment by a1batross** [comment]
And GCC not fails? :)

That's strange, if you get errors on `ndk-build` stage.

2016-05-10 19:11 GMT+03:00 Deic <notifications@github.com>:

**Comment by DeicPro** [comment]
nope.

The problem was a missing 32-bit compatibility that aapt need to works or something... IT stuff... ayy lmao XD
