### ISSUE TITLE
On-screen buttons are behind the weapon on first person view.

### ISSUE THREAD

**Issue by xDShot** [SDLash3D/xash3d-android-project#7]
![screenshot_2015-06-14-10-23-25](https://cloud.githubusercontent.com/assets/4261659/8230464/2892f55c-15c9-11e5-89f2-5b05b4640f4f.png)
![screenshot_2015-06-14-10-23-36](https://cloud.githubusercontent.com/assets/4261659/8230470/2fe801bc-15c9-11e5-972c-1e82ee7fe720.png)

It appears on Samsung Galaxy Gio (With Android 4.4.4 cyanogenmod). APK is ARMv6-version taken from 4pda.

**Comment by a1batross** [comment]
It appears everywhere.
It will be fixed in next release.

**Comment by a1batross** [comment]
Fixed.

**Comment by xDShot** [comment]
Thank you :)
