### ISSUE TITLE
Console text is too small.

### ISSUE THREAD

**Issue by atn2001** [SDLash3D/xash3d-android-project#70]
This really only occurs on phones with a hight pixel density like the samsung galaxy s4. It makes the text difficult to read.

**Comment by atn2001** [comment]
Well, I was a bit tired when I wrote this so excuse me for that. What I was trying to say was that if you are on a device with a high pixel density like a phone, the console text is so small to the point it is unreadable.

**Comment by a1batross** [comment]
It's isn't an issue. Working with fonts on Xash3D is terrible. 

I can say that you only can larger your hud by hud_scale cvar. But it doesn't affect console.
