### ISSUE TITLE
Half Life Lagging

### ISSUE THREAD

**Issue by SilverBullett** [SDLash3D/xash3d-android-project#71]
Hello dear developer, I'm really disappointed because of the lags that are happening during playing half life in online mode or when i join a lan game, its only not lagging if i was the owner of the create we are playing... how could this lag be solved to be able to play online again?

**Comment by SilverBullett** [comment]
Device is Xperia SP
Firmware Version is Marshmallow 6.0.1 (Custom ROM/Firmware)

**Comment by a1batross** [comment]
Enable client-side predicting by these console cvars:
cl_predict 1
cl_lw 1
cl_lc 1

These features still experimental and may give some problems in
singleplayer(like shaking trains).

2016-04-07 16:46 GMT+03:00 SilverBullett <notifications@github.com>:

**Comment by SilverBullett** [comment]
Thank you i tried those commands in the console and it seemed to work without lags but there is some stuttering and sometimes it writes in the righ side of the corner above ( Delta Frame is too old: overflow) after some minutes of the writing the commands you gave. hope you fix those lags in the next version without the need of writing those commands in the console

**Comment by SilverBullett** [comment]
And by the way, on my second device i dont have the console option in the main menu! how to enable it

**Comment by a1batross** [comment]
`-dev N` in command line, where is N is level.
1 is preferred for users.
2-3 shows warnings and errors.
4 shows libserver.
5 for engine developers.

Note that multiplayer support is still isn't good as you want.  We know about any multiplayer-related bug.
