### ISSUE TITLE
Can't change resolution in half life 1.

### ISSUE THREAD

**Issue by Slapturkey** [SDLash3D/xash3d-android-project#72]
So the game launches fine and I can access the videos settings menu and select a different resolution, however no effect takes place, and upon rebooting the application the settings have been reversed to default, in this case 1080p windowed mode, which is the native resolution of my device. If it helps my device has an adreno 405 gpu and an octa core snapdragon 615 cpu. At its current state it can run the game at around 20 fps which isnt really playable. Any help would be greatly appreciated. Thanks.

**Comment by a1batross** [comment]
You can change resolution of Android system. With root, ofc.

Yes, we know how slow Xash3D Android works on some devices. This caused by
bad OpenGLES1 drivers.

It's possible to switch to GLES2, which will give a good performance boost
on every device. But it's need to rewrite many code and it's very hard.

**Comment by Slapturkey** [comment]
I appreciate your insight however shouldn't i be able to change the resolution of the game without having to boot and completely change the native resolution of my device? It just doesn't make too much sense tome when people with much weaker/older devices can run the game fine. Any further suggestion to fix this or perhaps boost fps somehow? Or am i condemned  to 19 fps?

**Comment by a1batross** [comment]
We can use Frame Buffer Object. It's like rendering whole frame to fixed
resolution. After it become stretched to native resolution.

But it's requires GLES2, which we don't use. So it's impossible to change
resolution in-game now.

As temporarily solution, you can use GLTools. It's supports to change
resolution for one game.

**Comment by The-MAZZTer** [comment]
I don't believe Android allows apps to change resolution. There are root apps out there to do this for you if you really want it, but it's a system-wide setting.
