### ISSUE TITLE
Wrong coloring in Multiplayer

### ISSUE THREAD

**Issue by ET-NiK** [SDLash3D/xash3d-android-project#8]
Players in a multiplayer are painted incorrectly.

OS: Android 4.0.4
Phone: Sony Xperia U
Xash3D Android v0.14.1

![screenshot_2015-06-19-14-53-45](https://cloud.githubusercontent.com/assets/3670640/8253097/e2c041a2-1694-11e5-8b64-a704bb9f216d.png)

**Comment by mittorn** [comment]
It is engine related, maybe move it to xash3d repo?

**Comment by ET-NiK** [comment]
In xash3d all right. 
This bug only in xash3d-android

**Comment by a1batross** [comment]
Bug of SDL port of Xash. 

This is not affect original Xash3D engine.

**Comment by Mksands** [comment]
This has happened with me also, but I sort of fixed it by downloading hd player skins to replace them. They however don't change colors.

**Comment by a1batross** [comment]
Fixed in engine.
