### ISSUE TITLE
qwfwd (proxy support)

### ISSUE THREAD

**Issue by bmorello** [SDLash3D/xash3d-android-project#80]
There are qwfwd servers that would help the lag. I believe the client should have qwfwd on by default and there should be an option to turn it off in multiplayer.

https://github.com/jite/qwfwd

**Comment by a1batross** [comment]
I think it will not fix lags. But why not to try port it?(maybe without compability, because GS protocol != Xash protocol != QW protocol)

There is really need to fix network problems of Xash3D.

**Comment by bmorello** [comment]
Its used often for fte quake or ezquake... QW fwd fixes international lag mostly... But I understand :)
