### ISSUE TITLE
Xash Error

### ISSUE THREAD

**Issue by Syturio** [SDLash3D/xash3d-android-project#83]
When i install Xash3D it doesnt create a "xash" folder. And when i try to press "Launch Xash3D" it says: "Xash Error - Chaning working directory to ... failed."

(btw why did you close my last issue..?)

**Comment by a1batross** [comment]
Non-informative.

2016-04-18 20:24 GMT+03:00 Syturio <notifications@github.com>:

**Comment by Syturio** [comment]
Okey i managed to fix the error. But now when i try to open CS 1.6 client it gives me a error "couldnt find the game directory 'cstrike'" but its there... both cstrike and valve folders are there, why doesnt it work? '-'

**Comment by a1batross** [comment]
Lollipop or higher? You must have a button (select) in launcher. Press it and choose folder. It's only for permission.

**Comment by Syturio** [comment]
I using Samsung S3 Neo (Android 4.4.2). 

https://drive.google.com/file/d/0B5pY1_heLj8iWjM3N3Y2UXNhdUE/view?usp=sharing
https://drive.google.com/file/d/0B5pY1_heLj8iN01MNHhPWEx4dHc/view?usp=sharing
https://drive.google.com/file/d/0B5pY1_heLj8iQTFPQWh6cURnbTg/view?usp=sharing
https://drive.google.com/file/d/0B5pY1_heLj8iWkswMHpabHhZR1E/view?usp=sharing

What iam doing wrong?

**Comment by a1batross** [comment]
Try another place. For example, Android folder in sdcard.
Android/data/in.celest.xash3d.hl/files/.

I think it's a permission problems.

2016-04-18 21:43 GMT+03:00 Syturio <notifications@github.com>:

**Comment by Maitreblazius** [comment]
Same issue ...
"Xash Error - Chaning working directory to ... failed."

**Comment by Maitreblazius** [comment]
I haven't SD card but we can't put the game directly within the phone ?

**Comment by Syturio** [comment]
a1batross thanks, it worked.

**Comment by ayushhj79** [comment]
Plz provide me link for cs1.6 apk...
