### ISSUE TITLE
Screen is not updated

### ISSUE THREAD

**Issue by ThomasCZ** [SDLash3D/xash3d-android-project#9]
On SGS6 I have black screen all the time, but I can control everything

**Comment by a1batross** [comment]
Did you have latest 0.14.1 version?
Please, run this steps:
1) In xash/valve/gameinfo.txt set secure parameter to 0. It will enable
logging.
2) Attach engine.log (you can find it in /sdcard/xash) and adb logcat.

0:46, пт, 26.06.2015, ThomasCZ <notifications@github.com>:

**Comment by ThomasCZ** [comment]
There is only one line:
Error: listdirectory: scandir() failed, Unknown error -1 at valve/decals.wad/

**Comment by a1batross** [comment]
It's because you have not set "secure" to 0 in xash/valve/gameinfo.txt.

**Comment by ThomasCZ** [comment]
Oh sorry, there you are

Error: listdirectory: scandir() failed, Unknown error -1 at valve/decals.wad/execing video.cfg
execing opengl.cfg
Set: [2560x1440]
Error: VID_StartupGamma: hardware gamma unsupportedVideo: Mali-T760
Warning: GL_UploadTexture: cubemaps isn't supported, *vsdct ignored
AVI: Not supported
Using SDL audio driver: android @ 44100 Hz
Warning: CL_LoadProgs: couldn't get render API
1 joysticks found
Joystick 0 GUID is 416e64726f696420416363656c65726f
Could not find joystic mapping. Trying to register first joystick device 416e64726f696420416363656c65726f with default mapping
joystick found

**Comment by a1batross** [comment]
Strange. 

Generally, we have fixed most of "black screens" in 0.12, but you have latest version.

Also, can you give "logcat" info? It may be really big, so yo can post it to pastebin.

**Comment by ThomasCZ** [comment]
Everything from tap on launch xash3D!
http://pastebin.com/CES125Rw

**Comment by a1batross** [comment]
Hm... log seems doesn't show anything about your problem.

**Comment by ThomasCZ** [comment]
Could you send me some version with more debug info? Display is black, but others probably works. I can hear sounds and move in game, jumping,...

**Comment by a1batross** [comment]
I can only build a debug version for you, just attach a gdb and try to find
it by yourself.

I just doesn't have a SGS6 for testing.

23:41, пт, 26.06.2015, ThomasCZ <notifications@github.com>:
