### ISSUE TITLE
Textures not rendering correctly

### ISSUE THREAD

**Issue by SuperSamioWorld** [SDLash3D/xash3d-android-project#91]
v0.17 works perfectly on my Smartwatch 3, but on v0.17.1, almost none of the textures render correctly. Everything shows up black apart from some things like the sky and people.

[Here's a screenshot of what it looks like.](http://i.imgur.com/fB4L9Lw.png)

On my Z3 Compact and Shield Tablet it works as it should.

**Comment by a1batross** [comment]
We don't support smartwatches. It's a magic that engine works on it without
any memory errors.

2016-04-25 22:17 GMT+03:00 SuperSamioWorld <notifications@github.com>:

**Comment by SuperSamioWorld** [comment]
To be fair, Android Wear is (in my experience with it) just Android modified for a smaller screen, and to have a phone as a companion. I've been able to get almost anything I've tried to work on it as well as it did on my old phone, so if it's affecting the watch, it's most likely affecting some older devices.

I just want to be able to upgrade from the April fools release.

**Comment by a1batross** [comment]
There is only fixed glGetError().
Due to translator, it should be ignored and its ignored in all releases,
except v0.17.
Try to v0.16.1. And beta versions of v0.17.

2016-04-26 0:17 GMT+03:00 SuperSamioWorld <notifications@github.com>:
