### ISSUE TITLE
xash crash when add bot

### ISSUE THREAD

**Issue by duchbk123** [SDLash3D/xash3d-android-project#96]
i have problem that when i meet bot ( ct or t or all) i have crash :( pls help me solve this my bot use is from cs 1.6 non steam and zb bot

**Comment by duchbk123** [comment]
and sorry for my bad english :(

**Comment by fuzun** [comment]
logs?

**Comment by a1batross** [comment]
We doesn't meet any Non-Steam builds. 

Closing this, because xash3d-android-project is only for Xash3D Android related issues.
