### ISSUE TITLE
Joysticks (Xbox 360 controller and PS3 controller) crash the game sometimes (and dont work)

### ISSUE THREAD

**Issue by Jan200101** [SDLash3D/xash3d-android-project#97]
Name says the most was tested with xash3d and counter strike 1.6 client

**Comment by a1batross** [comment]
SDL2 bug.

Try to start the game with plugged in joystick and don't remove(or connect
any other) until engine is running.

2016-05-03 14:58 GMT+03:00 Jan200101 <notifications@github.com>:

**Comment by Jan200101** [comment]
@a1batross It workes... I can still do nothing except move around

**Comment by a1batross** [comment]
@Jan200101 just bind keys in game menu.

**Comment by Jan200101** [comment]
@a1batross I tried everywhere but I cant find anywhere. For example I go into the key binding menu (dunno if thats what its called but you know what I mean) I can highlight things like move left but not select or change them at all

**Comment by a1batross** [comment]
Changing buttons in menu is binded to Enter, Space and K_AUX30, K_AUX31.
AUX30 and AUX31 is a hardware volume keys on phone/tablet. Try these
buttons. You can enable it by setting "Use volume keys" to disabled state
in launcher(a mistake in code, will be fixed later))

Also you can change it in configuration files. Command is `bind K_AUXN
command`, where is N -- any number from 1 to 31 and commaid is command will
be executed on button press.
